### PR TITLE
Replaced the toSpliced method to something more generic

### PR DESCRIPTION
**Pull request by ig-66**
Replaced the toSpliced method to a more generic one, as toSplice is too recent (as of June 2023). so some frameworks and engines still do not support it.

### CODE REVIEW

**Comment by adankvitschal** [comment]
the proposed changes do not produce the same results, please check the usage of array 'slice' vs 's**p**lice'

**Comment by ig-66** [comment]
Changed the methods as asked, and tested it with NodeJS against the toSpliced examples in the Mozilla website, all of the console logs gave the same results as the examples.

The test script:
```js
function spliceAndConcat(array, start, deleteCount, ...items) {
	return array.slice(0, start).concat(items, array.slice(start + deleteCount));
}

const months = ["Jan", "Mar", "Apr", "May"];

// Inserting an element at index 1
const months2 = spliceAndConcat(months, 1, 0, "Feb");
console.log(months2); // ["Jan", "Feb", "Mar", "Apr", "May"]

// Deleting two elements starting from index 2
const months3 = spliceAndConcat(months2, 2, 2);
console.log(months3); // ["Jan", "Feb", "May"]

// Replacing one element at index 1 with two new elements
const months4 = spliceAndConcat(months3, 1, 1, "Feb", "Mar");
console.log(months4); // ["Jan", "Feb", "Mar", "May"]

// Original array is not modified
console.log(months); // ["Jan", "Mar", "Apr", "May"]
```
Output:
```
[ 'Jan', 'Feb', 'Mar', 'Apr', 'May' ]
[ 'Jan', 'Feb', 'May' ]
[ 'Jan', 'Feb', 'Mar', 'May' ]
[ 'Jan', 'Mar', 'Apr', 'May' ]
```

**Comment by adankvitschal** [comment]
the aux method name is kind of misleading, I'd like to suggest 3 changes:
-name the method to somethhing like 'deleteIndex' of maybe even 'toSpliced', I dont thin it would cause any conflict using the same name since it is a different scope.
-the argument deleteCount is not necessary, since the method will always delete only 1 host.
-merge the changes from master, otherwise it seems I will need to checkout it here and perform the changes myself.

**Comment by ig-66** [comment]
I have renamed the auxiliary function as asked, and as I renamed it to toSpliced, I have decided to keep the function as is, as it returns the same thing as toSpliced does.

**Pull request merged**
